<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array('jquery.easyui.extension/datagrid-detailview'),
        ));
        $ctrl_url = base_url('count/count_manager');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .dv-table td {
        border:0;
    }
    .dv-label {
        font-weight:bold;
        color:#15428B;
        width:100px;
    }
    .dv-table td {
        padding-bottom: 8px;
    }
    </style>
</head>
<body>
    <div id="p-dg" class="easyui-panel" title="订单报表管理" fit="true" border="false">
        <table id="dg" class="easyui-datagrid" title=""
               fit="true" border="false" plain="true"
               toolbar="#toolbar" multiSort="true"
               rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
               singleSelect="true" remote>
        </table>

        <div id="toolbar" style="padding:2px 3px;">
            <form id="fm-search" method="post" novalidate>
                <div style="margin:3px 0;">
                    <input type="hidden" id="step" name="step" value="1" />
                    申请人：
                    <select id="customer" class="easyui-combobox" style="width:200px;" name="customer" data-options="valueField:'id',textField:'showname'" panelHeight="auto" >
                    </select>
                    <span class="split-line">|</span>
                    <a class="easyui-linkbutton" iconCls="icon-search" onclick="do_search()" style="width:60px">搜索</a>
                </div>
            </form>
        </div>
    </div>

    <div id="p-dg1" class="easyui-panel" title="个人订单汇总" fit="true" border="false">
        <iframe id="manage_edit" style="width:100%;height:99%;border:0;" frameborder="0" scrolling="true" ></iframe>
    </div>

    <script type="text/javascript">
    $(function() {
        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj,
                columns:[[
                    {
                        field:'customername',
                        title:'申请人',
                        width:'250',
                        formatter: function(value){
                            console.log(value);
                            var html = '<a class="detailcls" icon="icon-search">'+ value +'</a>'
                            return html;
                        }
                    },{
                        field:'customer',
                        title:'客户id',
                        width:'100',
                        hidden: true,
                        formatter: function(value){
                            return value;
                        }
                    },{
                        field:'type_0',
                        title:'商标数',
                        width:'100',
                        formatter: function(value){
                            return value || '0';
                        }
                    },{
                        field:'type_1',
                        title:'专利数',
                        width:'100',
                        formatter: function(value){
                            return value || '0';
                        }
                    },{
                        field:'type_2',
                        title:'版权数',
                        width:'100',
                        formatter: function(value){
                            return value || '0';
                        }
                    },{
                        field:'type_3',
                        title:'其他数',
                        width:'100',
                        formatter: function(value){
                            return value || '0';
                        }
                    },{
                        field:'count_total',
                        title:'总计',
                        width:'100',
                        formatter: function(value, res){
                            return parseInt(res.type_0 || '0') + parseInt(res.type_1 || '0') + parseInt(res.type_2 || '0') + parseInt(res.type_3 || '0');
                        }
                    }
                ]],
                onLoadSuccess: function(){
                    $('.detailcls').linkbutton({plain:true,iconCls:'icon-search'});
                    $('.detailcls').on('click', function(){
                        setTimeout(open_detail, 100);
                    });
                }
            });
        }, 100);

        // 加载申请人下拉框
        $.ajax({
            url: "<?php echo $ctrl_url.'/customers'?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                new_data.push({"showname":"不限", "id":-1, "selected":true});
                $.each(data.rows, function(i, n) {
                    new_data.push({"showname":n.user_name, 'id': n.id});
                });
                $("#customer").combobox("loadData", new_data);
            }
        });

        $('#customer').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.showname.replace(/&nbsp;/ig, '');
                $('#customer').combobox('setText', n);
            }
        })
    });

    // 切换主面板
    function change_panel($name) {
        if($name=='dg') {
            $('#p-dg').panel('open');
            $('#p-dg1').panel('close');
        } else {
            $('#p-dg').panel('close');
            $('#p-dg1').panel('open');
        }
    }

    // 刷新面板
    function dg_reload(){
        $('#dg').datagrid('reload');
    }

    // 查看详情
    function open_detail() {
        var info = $('#dg').datagrid('getSelected');
        if(info==null) {
            $.messager.alert('操作提示', '请选择需要查看的记录！', 'warning');
            return;
        }
        var cur_tips_id = info['customer'];
        var url='<?php echo $ctrl_url.'/details/'?>' + cur_tips_id;
        $('#manage_edit').attr('src',url);
        change_panel('details');
    }

    // 搜索操作
    function do_search() {
        var fm_data = $('#fm-search').form('getData');
        $('#dg').datagrid('options').queryParams = {actionxm:'search', rs:fm_data};
        $('#dg').datagrid('reload');
    }

    </script>
</body>
</html>

