<!DOCTYPE html>
<html>
<head>
<?php
    $this->load->view('/public/linker',array(
        'css'=>array(),
        'js' =>array(),
    ));
    $ctrl_url = base_url('orders/order_undone_manager');
?>
<style>
    .required {
        color: red;
    }
    .fullwidth {
        width: 100%;
    }
    .dn {
        display: none;
    }
</style>
</head>
<body>
<div id="p-edit" class="easyui-panel" title="" fit="true" border="false">
    <div class="easyui-layout" fit="true">
        <div data-options="region:'north'" style="height:28px;overflow:hidden;background-color:#dddddd;" border="false">
            <button class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="javascript:window.parent.change_panel('dg');">返回</button>
        </div>
        <div data-options="region:'center'" style="overflow:hidden;" border="false">
            <div id="p-edit-login" class="easyui-panel" fit="true" border="false" style="overflow:auto;">
                <div class="easyui-panel" style="padding:15px 5px;">
                    <span><?php if($isend=='1'){echo "订单已完成";}else{echo "订单进行中";} ?></span>.
                    <span class="split-line">|</span>
                    <span><?php if(isset($applyid)){echo '订单号为：'.$applyid;} ?></span>.
                    <span class="split-line">|</span>
                    订单处理流程明细：
                </div>
                <table id="pg" style="width:100%"></table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function(){
        var applyid = "<?php echo $applyid; ?>";
        $('#pg').propertygrid({
            url: "<?php echo $ctrl_url.'/get?actionxm=stepsinfo&applyid=" + applyid + "'?>",
            showGroup: true,
            scrollbarSize: 0
        });
    })();

</script>

</body>
</html>
