<!DOCTYPE html>
<html>
<head>
<?php
    $this->load->view('/public/linker',array(
        'css'=>array(),
        'js' =>array(),
    ));
    $ctrl_url = base_url('orders/order_undone_manager');
?>
<style>
    .required {
        color: red;
    }
    .fullwidth {
        width: 100%;
    }
    .dn {
        display: none;
    }
</style>
</head>
<body>
<div id="p-edit" class="easyui-panel" title="" fit="true" border="false">
    <div class="easyui-layout" fit="true">
        <div data-options="region:'center'" style="overflow:hidden;" border="false">
            <div id="p-edit-login" class="easyui-panel" fit="true" border="false" style="overflow:auto;">
                <form id="fm-edit" method="post" style="width:90%; margin:10px;">
                    <input type="hidden" name="actionxm" value="<?php echo $actionxm; ?>" />
                    <input type="hidden" name="id" value="<?php echo get_value($info, 'id', '0'); ?>">
                    <input type="hidden" name="step" value="<?php echo 1; ?>" />
                    <input type="hidden" name="handelpoint" value="<?php echo 0; ?>" />
                    <table class="fm-table" cellpadding="8px">
                        <colgroup>
                            <col width="240px"  />
                            <col width="470px" />
                            <col width="*" />
                        </colgroup>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                申请名称：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="name" style="width:100%" data-options="required:true" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                申请人:
                            </td>
                            <td>
                                <select id="customer" class="easyui-combobox" style="width:200px;" name="customer" data-options="valueField:'id',textField:'showname'" panelHeight="auto" >
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                类型:
                            </td>
                            <td>
                                <select id="type" name="type" style="width:auto;">
                                    <option value="0" >商标</option>
                                    <option value="1" >专利</option>
                                    <option value="2" >版权</option>
                                    <option value="3" >其他</option>
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr class="dn">
                            <td class="label">
                                <span class="required">*</span>
                                是否减缓:
                            </td>
                            <td>
                                <select id="islater" name="islater" style="width:auto;">
                                    <option value="0" selected="selected">否</option>
                                    <option value="1" >是</option>
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                发票信息：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="billinfo" style="width:100%"/>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                收据信息：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="receiptinfo" style="width:100%;">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                下一步处理节点:
                            </td>
                            <td>
                                <select id="nextid" name="nextid" style="width:auto;">
                                    <!-- <option value="0" >订单管理（市场部）</option> -->
                                    <option value="1" selected="selected">任务处理（专利编制人）</option>
                                    <option value="2" >流程部（产权局沟通）</option>
                                    <option value="4" >财务缴费</option>
                                    <option value="5" >流程部（登记发文日）</option>
                                    <option value="6" >财务（确认完成交款）</option>
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                处理期限：
                            </td>
                            <td>
                                <input class="easyui-datebox" style="width:150px;" name="handeltime" id="handeltime" data-options="required:true">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                下一步责任人：
                            </td>
                            <td>
                                <select id="nexthandeler" class="easyui-combobox" style="width:200px;" name="nexthandeler" data-options="valueField:'user_id',textField:'true_name'" panelHeight="auto" >
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                备注：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="remark" id="remark" data-options="multiline:true" style="width:100%;height:80px">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center;" colspan="2">
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_save()">保存</button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_reset()">重置</button>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </form>
                <hr>
                <p>当前节点：订单管理（市场部）</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function(){
        $('#type').on('change', function(){
            if ($('#type')[0].value!="1") {
                $('#islater')[0].value = '0';
                $('#islater').closest('tr').addClass('dn');
            } else {
                $('#islater').closest('tr').removeClass('dn');
                $.parser.parse($('#islater').html());
            }
        });

        // 加载申请人下拉框
        $.ajax({
            url: "<?php echo $ctrl_url.'/customers'?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                new_data.push({"showname":"请选择", "id":-1, "selected":true});
                $.each(data.rows, function(i, n) {
                    new_data.push({"showname":n.user_name, 'id': n.id});
                });
                $("#customer").combobox("loadData", new_data);
            }
        });

        $('#customer').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.showname.replace(/&nbsp;/ig, '');
                $('#customer').combobox('setText', n);
            }
        });

        // 加载处理人下拉框
        $.ajax({
            url: "<?php echo base_url('sys/user/get?actionxm=get_list')?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                new_data.push({"true_name":"请选择", "user_id":-1, "selected":true});
                $.each(data, function(i, n) {
                    new_data.push({"true_name":n.true_name, 'user_id': n.user_id});
                });
                $("#nexthandeler").combobox("loadData", new_data);
            }
        });

        $('#nexthandeler').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.true_name.replace(/&nbsp;/ig, '');
                $('#nexthandeler').combobox('setText', n);
            }
        })
    })();

    // 保存登录tips信息
    function do_save() {
        $('#fm-edit').form('submit', {
            url: '<?php echo $ctrl_url; ?>/post',
            success: function(result) {
                var result = $.parseJSON(result);
                var actionxm = $('#fm-edit input[name="actionxm"]').val();
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    cur_tips_id = result.data.tips_id;
                    $('#fm-edit input[name="actionxm"]').val('update');
                    $('#fm-edit input[name="tips_id"]').val(cur_tips_id);
                    $.messager.alert('操作提示', '保存成功', 'info', function() {
                        // $('#p-edit').panel('open').panel('refresh');
                    });
                }
            }
        })
    }


</script>

</body>
</html>
