<!DOCTYPE html>
<html>
<head>
<?php
    $this->load->view('/public/linker',array(
        'css'=>array(),
        'js' =>array(),
    ));
    $ctrl_url = base_url('orders/order_undone_manager');
?>
<style>
    .required {
        color: red;
    }
    .fullwidth {
        width: 100%;
    }
    .dn {
        display: none;
    }
</style>
</head>
<body>
<div id="p-edit" class="easyui-panel" title="" fit="true" border="false">
    <div class="easyui-layout" fit="true">
        <div data-options="region:'north'" style="height:28px;overflow:hidden;background-color:#dddddd;" border="false">
            <button class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="javascript:window.parent.change_panel('dg');">返回</button>
        </div>
        <div data-options="region:'center'" style="overflow:hidden;" border="false">
            <div id="p-edit-login" class="easyui-panel" fit="true" border="false" style="overflow:auto;">
                <form id="fm-edit" method="post" style="width:90%; margin:10px;">
                    <input type="hidden" name="actionxm" value="<?php echo $actionxm; ?>" />
                    <input type="hidden" name="id" value="<?php echo get_value($info, 'id', '0'); ?>">
                    <input type="hidden" name="applyid" value="<?php echo get_value($info, 'applyid', '0'); ?>">
                    <input type="hidden" name="step" value="<?php echo get_value($info, 'step', '3'); ?>" />
                    <input type="hidden" name="handelpoint" value="2" />
                    <table class="fm-table" cellpadding="8px">
                        <colgroup>
                            <col width="240px"  />
                            <col width="470px" />
                            <col width="*" />
                        </colgroup>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                登记任务申请日：
                            </td>
                            <td>
                                <input class="easyui-datebox" style="width:150px;" name="registerdate" id="registerdate" data-options="required:true">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr class="js_back_step dn">
                            <td class="label">
                                <span class="required">*</span>
                                下一步处理节点:
                            </td>
                            <td>
                                <select id="nextid" name="nextid" style="width:auto;">
                                    <!-- <option value="0" >订单管理（市场部）</option> -->
                                    <option value="1" selected="selected">任务处理（专利工程师）</option>
                                    <!-- <option value="2" >流程部（申请流程）</option> -->
                                    <option value="4" >财务缴费</option>
                                    <option value="5" >流程部（中间文件）</option>
                                    <option value="6" >财务（确认完成交款）</option>
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr class="js_back_step dn">
                            <td class="label">
                                <span class="required">*</span>
                                处理期限：
                            </td>
                            <td>
                                <input class="easyui-datebox" style="width:150px;" name="handeltime" id="handeltime" data-options="required:false">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr class="js_back_step dn">
                            <td class="label">
                                <span class="required">*</span>
                                下一步责任人：
                            </td>
                            <td>
                                <select id="nexthandeler" class="easyui-combobox" style="width:200px;" name="nexthandeler" data-options="valueField:'user_id',textField:'true_name',required:true" panelHeight="auto" >
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center;" colspan="2">
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_save()">保存</button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button id="return_btn" type="button" class="easyui-linkbutton" style="width:90px" onclick="do_return()">回退</button>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </form>
                <hr>
                <p>当前节点：流程部（与产权局沟通前）</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function(){
        // 加载处理人下拉框
        $.ajax({
            url: "<?php echo base_url('sys/user/get?actionxm=get_list')?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                // new_data.push({"true_name":"请选择", "user_id":-1, "selected":true});
                $.each(data, function(i, n) {
                    new_data.push({"true_name":n.true_name, 'user_id': n.user_id});
                });
                $("#nexthandeler").combobox("loadData", new_data);
            }
        });

        $('#nexthandeler').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.true_name.replace(/&nbsp;/ig, '');
                $('#nexthandeler').combobox('setText', n);
            }
        })
    })();

    // 流程部产权局节点回退处理
    function do_return() {
        var $target = $('#return_btn');
        $target.linkbutton("disable");
        $('.js_back_step').removeClass('dn');
        $('#registerdate').closest('tr').addClass('dn');
    }

    // 保存登录tips信息
    function do_save() {
        $('#fm-edit').form('submit', {
            url: '<?php echo $ctrl_url; ?>/post',
            onSubmit: function() {
                if(!$('.js_back_step').hasClass('dn')) {
                    if($('input[name="handeltime"').val()=='') {
                        $.messager.alert('提示信息', '处理期限不可为空！', 'error');
                        return false;
                    }
                    if($('input[name="nexthandeler"').val()==-1) {
                        $.messager.alert('提示信息', '下一步责任人不可为空！', 'error');
                        return false;
                    }
                    return $(this).form('validate');
                } else {
                    if($('input[name="registerdate"').val()==-'') {
                        $.messager.alert('提示信息', '登记任务申请日不可为空！', 'error');
                        return false;
                    }
                }
            },
            success: function(result) {
                var result = $.parseJSON(result);
                var actionxm = $('#fm-edit input[name="actionxm"]').val();
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    cur_tips_id = result.data.tips_id;
                    $('#fm-edit input[name="actionxm"]').val('insert');
                    $('#fm-edit input[name="tips_id"]').val(cur_tips_id);
                    $.messager.alert('操作提示', '保存成功', 'info', function() {
                        window.parent.dg_reload();
                        window.parent.change_panel('dg');
                    });
                }
            }
        })
    }

</script>

</body>
</html>
