<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array('jquery.easyui.extension/datagrid-detailview'),
        ));
        $ctrl_url = base_url('orders/order_undone_manager');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .dv-table td {
        border:0;
    }
    .dv-label {
        font-weight:bold;
        color:#15428B;
        width:100px;
    }
    .dv-table td {
        padding-bottom: 8px;
    }
    </style>
</head>
<body>
    <div id="p-dg" class="easyui-panel" title="订单信息管理" fit="true" border="false">
        <table id="dg" class="easyui-datagrid" title=""
               fit="true" border="false" plain="true"
               toolbar="#toolbar" multiSort="true"
               rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
               singleSelect="true" remote>
        </table>

        <div id="toolbar" style="padding:2px 3px;">
            <form id="fm-search" method="post" novalidate>
                <div style="margin:3px 0;">
                    <input type="hidden" id="isend" name="isend" value="0" />
                    <input type="hidden" id="nexthandeler" name="nexthandeler" value="<?php echo $user_id; ?>"/>
                    申请名称：
                    <input id="name" class="easyui-textbox" style="width:100px" name="name">
                    申请人：
                    <select id="customer" class="easyui-combobox" style="width:100px;" name="customer" data-options="valueField:'id',textField:'showname'" panelHeight="auto" ></select>
                    流程发起人：
                    <select id="promoter_id" class="easyui-combobox" style="width:100px;" name="promoter_id" data-options="valueField:'id',textField:'showname'" panelHeight="auto" ></select>
                    类型：
                    <select id="type" class="textbox-text" name="type" style="width:80px;">
                        <option value="-1" selected="selected">不限</option>
                        <option value="0">商标</option>
                        <option value="1">专利</option>
                        <option value="2">版权</option>
                        <option value="3">其他</option>
                    </select>
                    <span class="split-line">|</span>
                    <a class="easyui-linkbutton" iconCls="icon-search" onclick="do_search()" style="width:60px">搜索</a>
                </div>
            </form>
        </div>
    </div>

    <div id="p-edit" class="easyui-panel" title="订单详情" fit="true" border="false">
        <iframe id="manage_edit" style="width:100%;height:99%;border:0;" frameborder="0" scrolling="true" ></iframe>
    </div>

    <script type="text/javascript">
    $(function() {
        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj,
                columns:[[
                    {
                        field:'applyid',
                        title:'订单号',
                        width:'250'
                    },{
                        field:'name',
                        title:'申请名称',
                        width:'190'
                    },{
                        field:'type',
                        title:'类型',
                        width:'40',
                        formatter: function(value) {
                            var rtn = '';
                            switch(value) {
                                case '0':
                                    rtn = '<span>商标</span>';
                                    break;
                                case '1':
                                    rtn = '<span>专利</span>';
                                    break;
                                case '2':
                                    rtn = '<span>版权</span>';
                                    break;
                                case '3':
                                    rtn = '<span>其他</span>';
                                    break;
                                default:
                                    rtn = '<span style="color:grey;">未知</span>';
                                    break;
                            }
                            return rtn;
                        }
                    },{
                        field:'customer',
                        title:'申请人',
                        width:'100'
                    },{
                        field:'nexthandeler',
                        title:'当前处理人',
                        width:'120'
                    },{
                        field:'handeltime',
                        title:'处理期限',
                        width:'100'
                    },{
                        field:'createtime',
                        title:'分配时间',
                        width:'100'
                    },{
                        field:'promoterName',
                        title:'流程发起人',
                        width:'100'
                    },{
                        field:'_opt',
                        title:'操作',
                        width:'120',
                        formatter: function(){
                            var html = '<a class="detailcls" icon="icon-search">查看</a>&nbsp;<a class="editcls" icon="icon-edit">处理</a>'
                            return html;
                        }
                    }
                ]],
                onLoadSuccess: function(){
                    $('.detailcls').linkbutton({text:'查看',plain:true,iconCls:'icon-search'});
                    $('.editcls').linkbutton({text:'处理',plain:true,iconCls:'icon-edit'});
                    $('.detailcls').on('click', function(){
                        setTimeout(open_detail, 100);
                    });
                    $('.editcls').on('click', function(){
                        setTimeout(open_operate, 100);
                    });
                }
            });
        }, 100);

        // 加载申请人下拉框
        $.ajax({
            url: "<?php echo $ctrl_url.'/customers'?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                new_data.push({"showname":"不限", "id":-1, "selected":true});
                $.each(data.rows, function(i, n) {
                    new_data.push({"showname":n.user_name, 'id': n.id});
                });
                $("#customer").combobox("loadData", new_data);
            }
        });

        $('#customer').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.showname.replace(/&nbsp;/ig, '');
                $('#customer').combobox('setText', n);
            }
        });

        $.ajax({
            url: "<?php echo $ctrl_url.'/get?actionxm=getPromoter'?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                console.log(data);
                var new_data = new Array();
                new_data.push({"showname":"不限", "id":-1, "selected":true});
                $.each(data, function(i, n) {
                    console.log(n);
                    new_data.push({"showname":n.user_name, 'id': n.user_id});
                });
                $("#promoter_id").combobox("loadData", new_data);
            }
        });

        $('#promoter_id').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.showname.replace(/&nbsp;/ig, '');
                $('#promoter_id').combobox('setText', n);
            }
        });
    });

    // 切换主面板
    function change_panel($name) {
        if($name=='dg') {
            $('#p-dg').panel('open');
            $('#p-edit').panel('close');
        } else {
            $('#p-dg').panel('close');
            $('#p-edit').panel('open');
        }
    }

    // 刷新面板
    function dg_reload(){
        $('#dg').datagrid('reload');
    }

    // 处理
    function open_operate() {
        var info = $('#dg').datagrid('getSelected');
        if(info==null) {
            $.messager.alert('操作提示', '请选择需要处理的记录！', 'warning');
            return;
        }
        var cur_tips_id = info['id'];
        var url = '<?php echo $ctrl_url.'/info/'?>' + cur_tips_id;
        $('#manage_edit').attr('src',url);
        change_panel('edit');
    }

    // 查看详情
    function open_detail() {
        var info = $('#dg').datagrid('getSelected');
        if(info==null) {
            $.messager.alert('操作提示', '请选择需要查看的记录！', 'warning');
            return;
        }
        var cur_tips_id = info['applyid'];
        var url='<?php echo $ctrl_url.'/details/'?>' + cur_tips_id;
        $('#manage_edit').attr('src',url);
        change_panel('details');
    }

    // 搜索操作
    function do_search() {
        var fm_data = $('#fm-search').form('getData');
        $('#dg').datagrid('options').queryParams = {actionxm:'search', rs:fm_data};
        $('#dg').datagrid('reload');
    }

    // 格式化订单类型
    function format_type(value) {
        var rtn = '';
        switch(value) {
            case '0':
                rtn = '<span>商标</span>';
                break;
            case '1':
                rtn = '<span>专利</span>';
                break;
            case '2':
                rtn = '<span>版权</span>';
                break;
            case '3':
                rtn = '<span>其他</span>';
                break;
            default:
                rtn = '<span style="color:grey;">未知</span>';
                break;
        }
        return rtn;
    }

    </script>
</body>
</html>

